default['jboss']['install_path'] = '/opt'
default['jboss']['package_url'] = 'http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip'
default['jboss']['jboss_user'] = 'jboss'
default['jboss']['jboss_group'] = 'jboss'
default['jboss']['admin_user'] = 'admin'
default['jboss']['admin_passwd'] = 'admin'
default['jboss']['install_dir'] = '/jboss-as-7.1.1.Final'